### ISSUE TITLE
Multiline text - overflows boundaries with long continuous strings

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pyfontstash#3]
@mkassner - Multiline text overflows boundaries when there is a long continuous string, like a file path. See screenshot: 
![screen shot 2015-04-15 at 13 12 41](https://cloud.githubusercontent.com/assets/1407224/7153134/9c4cacde-e371-11e4-9a06-cc36dc97cf6b.png)

**Comment by mkassner** [comment]
this is mostly fixed please pull pyglui/pyfontstash changes from yesterday.

But:
It only solves the obvious bug. The long single path is tricky because how do we decide to where and if break a long word? Maybe this should be addressed in the design of the text field (don't show the string) and not the multiline text implementation.
